//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocCachShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiBanHangEntities : DbContext
    {
        public QuanLiBanHangEntities()
            : base("name=QuanLiBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAnh> tAnh { get; set; }
        public virtual DbSet<tChatLieu> tChatLieu { get; set; }
        public virtual DbSet<tDanhMucSP> tDanhMucSP { get; set; }
        public virtual DbSet<tDonHang> tDonHang { get; set; }
        public virtual DbSet<tHangSX> tHangSX { get; set; }
        public virtual DbSet<tKhachHang> tKhachHang { get; set; }
        public virtual DbSet<tLoaiSP> tLoaiSP { get; set; }
        public virtual DbSet<tMauSac> tMauSac { get; set; }
        public virtual DbSet<tNhanVien> tNhanVien { get; set; }
        public virtual DbSet<tVanChuyen> tVanChuyen { get; set; }
        public virtual DbSet<tVideo> tVideo { get; set; }
        public virtual DbSet<tChiTietHDB> tChiTietHDB { get; set; }
        public virtual DbSet<tChiTietMau> tChiTietMau { get; set; }
        public virtual DbSet<tDanhGia> tDanhGia { get; set; }
    }
}
